export const ActionTypes = {
  //Harshaavardhini
  SET_USER: 'SET_USER',
  SET_LOGIN: 'SET_LOGIN',
  SET_LOGOUT: 'SET_LOGOUT',

  //Kashyap
  SET_NAME: 'SET_NAME',
  SET_AVATAR: 'SET_AVATAR',

  //Sammed
  SET_STARRED_MESSAGES: 'SET_STARRED_MESSAGES',
  REMOVE_STARRED_MESSAGES: 'REMOVE_STARRED_MESSAGES',
  REPLY_MESSAGE: 'REPLY_MESSAGE',
  DELETE_REPLY_MESSAGE: 'DELETE_REPLY_MESSAGE',
};
